site_name: MediLink

theme:
  name: material
  logo: images/logo.jpeg
  palette:
    - scheme: default
      primary: green
      accent: deep orange

nav:
  - Overview: index.md
  - Introduction: introduction.md
  - Functional Use Cases: functional_usecase.md
  - Bussiness Use Cases: usecases.md

plugins:
  - search
  - mermaid2
