site_name: MediLink

theme:
  name: material
  logo: images/logo.jpeg
  palette:
    - scheme: default
      primary: green
      accent: deep orange

nav:
  - Overview: index.md
  - Introduction: introduction.md
  - Functional Use Cases: functional_usecase.md
  - Bussiness Use Cases: usecases.md
  - Technical Design:
      - Schema Design: schema_design.md
      - Architecture: technical/AWS.md
      - Data Flow Diagram: technical/Data_Flow.md
      - Technical Stack: technical/Technical_Stack.md
      - Authentication and Authorization: technical/Access.md
      - Test Plan: technical/test.md
      - Doctor Slot Management: technical/doctor_slot.md
      - Appointment Booking: technical/appointment_booking.md
  - Test Report: Testreports.md
      

plugins:
  - search
  - mermaid2
